version: "3.3"
services:
  allure_report:
    build:
      context: .
      dockerfile: ./AllureReport/Dockerfile
    container_name: allure_report #"${CONTAINER_NAME_2}"
    networks:
    - myTestNetwork
    volumes:
    - allurenewman:/allurenewman/
#    depends_on:
#    - newman_collection
    profiles:
    - generate_report
networks:
  myTestNetwork:
    driver: bridge

volumes:
  allurenewman:
# создает образ dockernewman_allurenewman , понять как сделать правильно
